### PR TITLE
CDT.setup working set definitions: fix swapped LSP and LLVM

### PR DESCRIPTION
**Pull request by ruspl-afed**
Fix working set predicate patterns for "CDT LLVM" and "CDT LSP"

### CODE REVIEW

**Comment by ruspl-afed** [comment]
@jonahgraham do you know the cause of delays in pipelines?

**Comment by ruspl-afed** [comment]
> PS. You may need to raise an issue with the [helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new) to delete the branch once you have merged it.

Oops, I thought branch deletion is allowed for committers, except "protected" branches.

**Review by jonahgraham — APPROVED** [review]
LGTM.

I don't think you need to wait for CI to merge this as CDT.setup changes are completely untested by any automated flow.

**Comment by ruspl-afed** [comment]
> PS. You may need to raise an issue with the [helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new) to delete the branch once you have merged it.

Done. https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2148

**Pull request merged**
