### PR TITLE
Improve encapsulation within AbstractGnuToolPrefixMacro

### PR DESCRIPTION
**Pull request by jld01**
Part of #361

### CODE REVIEW

**Comment by gmiossec29** [comment]
Hi,

this commit seems to break my usage of cdt 11.2
org.eclipse.cdt.managedbuilder.macros.AbstractGnuToolPrefixMacro cannot be found in cdt 11.2 tag

**Comment by jonahgraham** [comment]
The file is there on the branch - https://github.com/eclipse-cdt/cdt/blob/cdt_11_2/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/macros/AbstractGnuToolPrefixMacro.java and tag https://github.com/eclipse-cdt/cdt/blob/CDT_11_2_0/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/macros/AbstractGnuToolPrefixMacro.java

However it seems that GitHub indexing isn't working because if I type AbstractGnuToolPrefixMacro in the search it says it is not there:

image

I have filed a bug report with GitHub on this issue - but I think the link is private https://support.github.com/ticket/personal/0/2276662

**Comment by gmiossec29** [comment]
I have errors for projects which are using cdt. Log says [....]Caused by: java.lang.ClassNotFoundException: org.eclipse.cdt.managedbuilder.macros.AbstractGnuToolPrefixMacro cannot be found by org.eclipse.cdt.build.crossgcc_1.3.100.202304191745$

**Comment by jonahgraham** [comment]
It looks like there is a mix and match of version here. AbstractGnuToolPrefixMacro is a new class in CDT 11.2 so I wonder if you have a partially updated CDT install (indicating a bug in the update process) or something else going on. We don't support mixing and matching bundles across CDT releases, but sometimes the auto update mechanism fails us.

Can you please provide more details, e.g. how to reproduce this and maybe the full stack trace too.

I see a potential problem in https://github.com/eclipse-cdt/cdt/blob/b2666eb57819b3e22b22bf05f586caa95dc34df4/cross/org.eclipse.cdt.build.crossgcc/META-INF/MANIFEST.MF#L8

The crossgcc has as a minimum version 9.2, but AbstractGnuToolPrefixMacro is in 9.6+.

**Comment by jld01** [comment]
> The crossgcc has as a minimum version 9.2, but AbstractGnuToolPrefixMacro is in 9.6+.

I will update the minimum version string.

**Comment by gmiossec29** [comment]
> 

I downgraded cdt to version 11.1 to be able to use my eclipse projects.
I tried to upgrade again to 11.2 to give you more info. And now... it's works !

It was certainly a migration error...

**Comment by jonahgraham** [comment]
Thanks for trying again and for raising this issue. With what John plans for version constraints should mean future users aren't affected.

**Comment by gmiossec29** [comment]
Thanks for your help !

**Comment by jonahgraham** [comment]
> The file is there on the branch - https://github.com/eclipse-cdt/cdt/blob/cdt_11_2/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/macros/AbstractGnuToolPrefixMacro.java and tag https://github.com/eclipse-cdt/cdt/blob/CDT_11_2_0/build/org.eclipse.cdt.managedbuilder.core/src/org/eclipse/cdt/managedbuilder/macros/AbstractGnuToolPrefixMacro.java
> 
> However it seems that GitHub indexing isn't working because if I type AbstractGnuToolPrefixMacro in the search it says it is not there:
> 
> image
> 
> I have filed a bug report with GitHub on this issue - but I think the link is private https://support.github.com/ticket/personal/0/2276662

This has a probable fix sitting in #518

**Pull request merged**
