### PR TITLE
[#385] Employ Eclipse Dash license check

### LINKED ISSUE #385: Employ Eclipse Dash license check
Let's try to automate 3rd party license check

### PR DESCRIPTION
**Pull request by ruspl-afed**
Add yml configuration to check licenses

Fixes #385

### CODE REVIEW

**Comment by jonahgraham** [comment]
LGTM - but please don't merge it until the current failures are addressed.

**Comment by waynebeaton** [comment]
In the future, use the [Automatic IP Team Review](https://github.com/eclipse/dash-licenses#automatic-ip-team-review-requests) feature to create review request issues and the IP Team will take it from there. 

There's actually two things happening here.

The EMF features are an oversight. I've added a hint that will make the license tool recognise these as belonging to the EMF project (so you shouldn't see them when you run the tool).

The others are, AFAICT, Orbitified versions of third party content that's been approved. There was an unintended consequence of removing the `ip_log.xml` files. The short version is that we used information in that file to help us hint some of the mappings from Orbitified JARs to the corresponding GAV. When you run the license tool against Orbit, it's checking for license information using the standard GAV; it then makes the Orbitified content available via a (sometimes) very different identifier. 

I am investigating a solution.

**Comment by ruspl-afed** [comment]
> In the future, use the [Automatic IP Team Review](https://github.com/eclipse/dash-licenses#automatic-ip-team-review-requests) feature to create review request issues and the IP Team will take it from there.

Sorry for breaking your process, will do next time. I was not sure what to do for EMF, because if I launch `-review` for entry like `p2/orbit/p2.eclipse.feature/org.eclipse.emf.common/2.29.0.v20230315-1321` IP Bot usually cannot find source automatically.

**Comment by ruspl-afed** [comment]
Now we have another set of reported issues:
```
[INFO] p2/orbit/p2.eclipse.plugin/javax.ws.rs/2.1.6.v20221203-1659
[INFO] p2/orbit/p2.eclipse.plugin/org.bouncycastle.bcpkix/1.72.0.v20221013-1810
[INFO] p2/orbit/p2.eclipse.plugin/org.bouncycastle.bcutil/1.72.0.v20221013-1810
[INFO] p2/orbit/p2.eclipse.plugin/org.junit.jupiter.api/5.9.1.v20221103-2317
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.equinox.executable_root.cocoa.macosx.aarch64/3.8.2100.v20230307-1841
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.equinox.executable_root.cocoa.macosx.x86_64/3.8.2100.v20230307-1841
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.equinox.executable_root.gtk.linux.aarch64/3.8.2100.v20230307-1841
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.equinox.executable_root.gtk.linux.ppc64le/3.8.2100.v20230307-1841
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.equinox.executable_root.gtk.linux.x86_64/3.8.2100.v20230307-1841
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.equinox.executable_root.win32.win32.x86_64/3.8.2100.v20230307-1841
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.platform_root/4.28.0.v20230405-1811
[INFO] p2/orbit/p2.p2.installable.unit/org.eclipse.rcp_root/4.28.0.v20230405-1811
```

**Comment by jonahgraham** [comment]
> I am investigating a solution.

xref https://bugs.eclipse.org/bugs/show_bug.cgi?id=581504#c4 (Specifically comment 4+5)

**Comment by waynebeaton** [comment]
> IP Bot usually cannot find source automatically.

But id does give us a kick in the arse to sort out a solution.

**Comment by ruspl-afed** [comment]
Thank you @waynebeaton UIs from Platform are not in the list anymore

**Comment by ruspl-afed** [comment]
> > I am investigating a solution.
> 
> xref https://bugs.eclipse.org/bugs/show_bug.cgi?id=581504#c4 (Specifically comment 4+5)

GAV is not helpful for me here.

for Jupiter it says
```
$ echo "org.junit.jupiter:junit-jupiter-api:5.9.1" | java -jar org.eclipse.dash.licenses-0.0.1-20230417.051435-801.jar -
[main] INFO Querying Eclipse Foundation for license data for 1 items.
[main] INFO Found 1 items.
[main] INFO Vetted license information was found for all content. No further investigation is required.
```
and I cannot request a review

For others, that seems to be collected from [Linux Tools](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/master/releng/org.eclipse.linuxtools.target/linuxtools-e4.28.target#L24) there is no literal Maven substitution. 
Not sure what should I do next:

1) Try to switch Linux Tools to consume these jars from Maven directly
or
2) Submit issues for IP Team and wait for the fix 

WDYT @jonahgraham ?

**Comment by waynebeaton** [comment]
> GAV is not helpful for me here.

The pointer was for me. I am testing a solution that will recognise `p2/orbit/p2.eclipse.plugin/org.junit.jupiter.api/5.9.1.v20221103-2317` as `org.junit.jupiter:junit-jupiter-api:5.9.1`. I'll roll it out shortly. 

I've added some hints to the database to correctly map the other four issues, so you should be all clear. I've confirmed this.

--

While it would be grand if the automation worked perfectly and always comes up with the right answer, this will never be the case. As we discover these sorts of issues (and work through periodic unfortunate regressions), the quality of the answers will get better. But... if the license tool is telling you something that you know is false, then you are under no obligation to try and satisfy the license tool.

I personally don't like the idea of configuring a build to fail based on the results of the Eclipse Dash License Tool, and recommend against it. I really don't want committers taking extraordinary measures to satisfy the tool.

When the output of the tool is telling you something that doesn't seem right, please open an issue on the Eclipse Dash License Tool and we'll work through it. If you don't trust what the tool is telling you, then connect with the IP Team for assistance.

**Comment by ruspl-afed** [comment]
> I've added some hints to the database to correctly map the other four issues, so you should be all clear.

Thank you so much @waynebeaton !

> I personally don't like the idea of configuring a build to fail based on the results of the Eclipse Dash License Tool, and recommend against it

I respectfully disagree. If the build does not fail due to a license check violation, the practical value is significantly reduced, since almost no one will view the log of the passed check.

 > I really don't want committers taking extraordinary measures to satisfy the tool

What committers need is a [sequence of] stable build[s] of Eclipse Dash License Tool, so every project could freeze for a while the version that works for it. And thank you for [working on it](https://github.com/eclipse/dash-licenses/issues/232#issuecomment-1527564577). 

> When the output of the tool is telling you something that doesn't seem right, please open an issue on the Eclipse Dash License Tool and we'll work through it.

Will do so, I was not sure which channel is preferable since I had no answer [here](https://github.com/eclipse/dash-licenses/issues/225) until I found a solution myself.

> If you don't trust what the tool is telling you, then connect with the IP Team for assistance.

I think you are talking about [IP Lab issues](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/) here

Thank you again for your effort @waynebeaton , Eclipse Dash License Tool is already helping committers a lot!

**Comment by waynebeaton** [comment]
> What committers need is a [sequence of] stable build[s] of Eclipse Dash License Tool, so every project could freeze for a while the version that works for it. 

FWIW, this issue has nothing to do with the front end.

With the exception of the change described in [issue 232](https://github.com/eclipse/dash-licenses/issues/232#issuecomment-1527564577), the Eclipse Dash License Tool itself has been basically stable for months. Most of the "fixes" have been updates to metadata, adding validation of the project id, and other things that basically have nothing to do with actual license resolution. The nature of the tool is that front-end will basically not likely change very much. We may add additional features to, say, generate or update SBOMs, but the fundamental license resolution behaviour shouldn't need to change.

The data sources that feed the tool, including ClearlyDefined and the Dash backend continuously change. I regard this as a feature, not a bug, so we will make no attempt to stabilise any of it.

Both of our current data sources tend towards greater accuracy over time. In practice we tend evolve data to provide better license information resulting in subtle changes in license expressions. At least in theory, there is always going to be some risk that we may identify licenses in content that revokes the approved state.

Note that it has been the case that previously approved content could have its status changed when new information is discovered (this predates the Eclipse Dash License Tool by at least a decade).

**Pull request merged**
