### PR TITLE
Support arguments and working directory in launching Core Build proje…

### PR DESCRIPTION
**Pull request by ewaterlander**
…cts for Local

Added the CArgumentsTab to the Core Build launch configuration for the Local target. This enables users to set command line arguments and specify a working directory.

### CODE REVIEW

**Comment by ewaterlander** [comment]
image

**Comment by ewaterlander** [comment]
Hi @betamaxbandit ,
would you like to review?

**Comment by ewaterlander** [comment]
Note this fixes all 4 flavors of Core Build projects: CMake, Makefile, Autotools, Arduino.

**Comment by ewaterlander** [comment]
> Hi @ewaterlander , Yes I'll review this. Hopefully will get to it soon. Cheers John

Thanks!
I think the failing tests are not caused by my change. I see no relation. I think these failures are caused by timeouts.

**Comment by ewaterlander** [comment]
Should I trigger a new build?
What's actually the best way to do that? What I would do now is a git amend with a small change of the commit message and then a push -f.

**Comment by betamaxbandit** [comment]
> Should I trigger a new build? What's actually the best way to do that? What I would do now is a git amend with a small change of the commit message and then a push -f.

Hi @ewaterlander ,
yes that's what I did the other day for mine.

**Comment by ewaterlander** [comment]
Build is still broken.

**Comment by jonahgraham** [comment]
I re triggered the licensing check, the 8 errors/60 fails is #816

**Review by betamaxbandit — COMMENTED** [review]
LGTM

**Comment by ewaterlander** [comment]
Hi,
Is merging on hold? What should I do?

**Comment by betamaxbandit** [comment]
> Hi, Is merging on hold? What should I do?

Hi @ewaterlander ,
I also have some patches which I'm waiting to be merged, so I expect @jonahgraham may be away on vacation.

Cheers John

**Comment by ewaterlander** [comment]
I retriggerd a build. I hope this PR can get merged soon.

**Pull request merged**
