### PR TITLE
Filter nested projects from org.eclipse.cdt.root

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-cdt/cdt/issues/37

### CODE REVIEW

**Review by ruspl-afed — APPROVED** [review]
LGTM. Thank you Ed @merks !

**Comment by merks** [comment]
@ruspl-afed   Can this be merged now so that I can submit my next PR for more setup changes based on top of this?

**Comment by ruspl-afed** [comment]
test failures seems unrelated, merging

**Comment by merks** [comment]
@ruspl-afed  Thanks.

**Pull request merged**
