### PR TITLE
Swapped arguments

### PR DESCRIPTION
**Pull request by ewaterlander**
Fixed swapped arguments in call of new ExtendedScannerInfo().

### CODE REVIEW

**Comment by jonahgraham** [comment]
Can you explain the effect of this change - i.e. is this critical, should we be releasing an emergency patch, or other?

**Comment by jonahgraham** [comment]
PS As soon as I get #554 resolved we can merge this for the 11.4 branch which release in Dec. My question is if we need to emergency patch the 11.3.0 release that was this week and release a 11.3.1 that has this fix?

**Comment by ewaterlander** [comment]
> My question is if we need to emergency patch the 11.3.0 release that was this week and release a 11.3.1 that has this fix?

Hi Jonah,

This problem was found by a static code analysis tool. I did not notice the problem myself. As far as I'm concerned, it's not necessary to make an emergency patch. And I'm still working with CDT 10.x, so I work with a local patch anyway.

I ran static code analysis on a few CDT source files which I needed to change for my plugin. It found another (small) problem in the same file which I'm going to upload too.

**Comment by jonahgraham** [comment]
@ewaterlander I rebased this on main now that #551 is fixed - once CI checks pass this can be merged.

**Review by jonahgraham — APPROVED** [review]

**Comment by jonahgraham** [comment]
Test failiure is known flaky #194

**Comment by jonahgraham** [comment]
Thanks @ewaterlander for the fix.

**Pull request merged**
