### PR TITLE
Add ManagedBuildManager#createConfigurationForProject()

### PR DESCRIPTION
**Pull request by 15knots**
This should allow ISV's to create MBS based project with a vendor-specific build-system ID without using internal API.

Signed-off-by: Martin Weber <11367029+15knots@users.noreply.github.com>

### CODE REVIEW

**Comment by jonahgraham** [comment]
I added this unrelated test failure to #117 as:

- #128

**Review by jonahgraham — CHANGES_REQUESTED** [review]
As this involves new public API that is useful for ISVs, please include a N&N entry in [CDT 11's N&N](https://github.com/eclipse-cdt/cdt/blob/main/NewAndNoteworthy/CDT-11.0.md)

---

Can you please update this to not have all the unrelated comment changes please. This change is >1500 lines of code change as it is now, causing GitHub not to render diff by default and it is not easy to spot what code changes have been made.

Initially when we formatted all the code we left comments as do not format. It looks like you are using some custom formatter settings (as opposed to the project settings) which causes formatting of unrelated code.

I am open to changing the CDT defaults to include comment formatting, but I want to handle that in a separate commit/PR please.

**Comment by 15knots** [comment]
Sorry for the noise. The formatting rules of CDT now give me 20 unrelated changes.
Any of them is a empty line in comment-out code. These lines now are formatted as '	 * '.
I hope that will be OK.

**Comment by jonahgraham** [comment]
20 lines is fine for me, we can see those changes easily enough. Not sure why the files are having any changes though, but as JDT versions change the formatting sometimes changes even though settings aren't changed. If we are seeing a lot of this I can deal with it down the line.

**Comment by 15knots** [comment]
Ah, again this weird reformatting.
Ok installing the IDE again using OOMPH didn't the trick.
Guess I should abandon this and restart with a fresh clone

**Pull request closed without merging**
