### PR TITLE
Amend list initialization sequence

### PR DESCRIPTION
**Pull request by i-garrison**
- add more tests for list-initialization of class or aggregate
- amend list-initialization handling of class or aggregate

### CODE REVIEW

**Comment by i-garrison** [comment]
Hi @jonahgraham - hope this CI build issue is transient?
> Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.31-0ubuntu9.9_amd64.deb

**Comment by jonahgraham** [comment]
> Hi @jonahgraham - hope this CI build issue is transient?
> 
> > Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.31-0ubuntu9.9_amd64.deb

There was a missing apt update in our script - fixed in #586 - please rebase changes once I merge #586 to pick up the fix.

**Comment by jonahgraham** [comment]
(My commit message in #586 referenced this PR in a way that caused it to be auto-closed. Re-opening)

**Comment by i-garrison** [comment]
Hi @jonahgraham would you believe we can get this merged before 11.4.0 cutoff date?

Mind that #448 is conflicting with his one but we have an agreement to prefer this (larger) change https://github.com/eclipse-cdt/cdt/pull/448#issuecomment-1751835855

**Review by jonahgraham — APPROVED** [review]
At recent [CDT calls](https://hackmd.io/@jonahgraham/EclipseCDTCalls) we discussed how to handle reviews where there is insufficient expertise to review amongst existing committers and decided to accept such changes that look reasonable and appear sufficiently tested.

I have pushed a rebased version of this change.

**Comment by jonahgraham** [comment]
I bumped the cdt.ui and updated the dep on cdt core to make sure the method with the new parameter is properly picked up.

**Pull request merged**
