### PR TITLE
[#693] Fix resource leak warnings for org.eclipse.cdt.core.utils

### LINKED ISSUE #693: Fix resource leak warnings for org.eclipse.cdt.core.utils
We have several "resource leak" warnings for `Dwarf` and `MachO64` types

It would be good to fix them

### PR DESCRIPTION
**Pull request by ruspl-afed**
* use `try-with-resources` for `AutoCloseable`

Fixes #693

### CODE REVIEW

**Comment by ruspl-afed** [comment]
@jld01 we have more hidden resource leak issues near `Dwarf` and related types when exposing them via `ISymbolReader` adapter: it is really not clear when to close them properly. Idea to override `finalize` is not good for Java, since the usage of this method was deprecated long ago. But these seem to be out of scope here, since most probably the proper the fix will cause breaking API changes.

**Review by jld01 — COMMENTED** [review]
These changes look positive, @ruspl-afed, but I'm struggling to understand why the `dispose()` methods are necessary in the first place. For example, the `Dwarf` section maps should fall out of scope with each `Dwarf` instance. Do you have any insight into what is preventing the garbage collector from doing its job here?

**Review by jonahgraham — APPROVED** [review]
The history of why it needs to be autocloseable and not wait until gc runs is in https://github.com/eclipse-cdt/cdt/pull/132

But the short answer is that all these classes hold onto real files so waiting until gc is too late.

**Comment by jld01** [comment]
Thanks for the explanation, @jonahgraham. 👍

**Review by jld01 — APPROVED** [review]

**Pull request merged**
