### PR TITLE
[#657] CDT cannot be built on Java 21 due to security manager changes

### LINKED ISSUE #657: CDT cannot be built on Java 21 due to security manager changes
**Describe the bug**
On Java 21 the Maven build of CDT fails in every Maven module that needs to run Ant. I'm not sure if this failure is currently even relevant for the CDT project, since building on Java 17 continues to work fine. I'm fine with closing as "not relevant yet".

**To Reproduce**
```
cd cdt-root
set JAVA_HOME=your-jdk-21-location
mvn verify
```

**Screenshots**
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (generate-configuration) on project org.eclipse.cdt.debug.application: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] C:\dev\cdt-main\git\cdt\debug\org.eclipse.cdt.debug.application\configGenerator.xml:4: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
[ERROR] around Ant part ...<ant antfile="configGenerator.xml" target="generate.configuration" />... @ 6:74 in C:\dev\cdt-main\git\cdt\debug\org.eclipse.cdt.debug.application\target\antrun\build-main.xml
```

**Version Information (please complete the following information):**
HEAD

**Additional context**
There was a discussion somewhere in platform about Ant being problematic on Java 21, because the exception handling of the Ant plugin in Eclipse relies on the security manager to capture the "exit" of the embedded Ant. That's probably exactly the same issue.

### PR DESCRIPTION
**Pull request by ruspl-afed**
* Switch CI to Java 21
* Remove config generation for debug application
* Remove `org.eclipse.osgi.services` from `proxy.server` product
* Remove `org.eclipse.osgi.services` from
`org.eclipse.cdt.debug.application.product` product
* Move `org.eclipse.cdt.debug.application.product` from profile to
general part

Fixed #657

### CODE REVIEW

**Comment by ruspl-afed** [comment]
What if we include [<module>debug/org.eclipse.cdt.debug.application.product</module>](https://github.com/eclipse-cdt/cdt/blob/96a3310420176655286d84fb8f24383949616e72/pom.xml#L412) back to the general modules list @jonahgraham ?

Currently it is outside of the CI control.

**Comment by ruspl-afed** [comment]
Well, no idea if Debug RCP is fully functional, but it starts after building locally from this branch
image

**Comment by ruspl-afed** [comment]
Merging this one to unblock further development in `main` branch

**Comment by jonahgraham** [comment]
> What if we include [debug/org.eclipse.cdt.debug.application.product](https://github.com/eclipse-cdt/cdt/blob/96a3310420176655286d84fb8f24383949616e72/pom.xml#L412) back to the general modules list @jonahgraham ?
> 
> Currently it is outside of the CI control.

Sorry that I missed this before. It was in its own profile because it is so fragile that it comes in and out of the main build regularly.

> Remove config generation for debug application

I don't understand how debug application works if this is removed? The install script won't be able to find the config.ini:

https://github.com/eclipse-cdt/cdt/blob/2c3f1110cabdb25a6cf961ebe07cfb4ec099b452/debug/org.eclipse.cdt.debug.application/scripts/install.sh#L44

The screenshot you took in https://github.com/eclipse-cdt/cdt/pull/761#issuecomment-2066922115 - how was that created? Was it with https://github.com/eclipse-cdt/cdt/blob/main/StandaloneDebugger.md

I'm about to raise an issue on standalone debugger and will cross reference this issue. Frankly I think my proposal is to remove it now or soon, so don't spend too much time addressing the above questions.

**Pull request merged**
