### PR TITLE
Add definitions for integer overflow builtins from GCC

### LINKED ISSUE #271: Builtin integer overflow functions not known
GCC has a set of [builtin functions](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html) for performing integer arithmetic with overflow checking, for example `__builtin_sadd_overflow` etc. These are not present in [CDT's list of builtin functions](https://github.com/eclipse-cdt/cdt/blob/a4ba7173e8b882fdeaa42255f764ec00301f4cb1/core/org.eclipse.cdt.core/parser/org/eclipse/cdt/internal/core/dom/parser/GCCBuiltinSymbolProvider.java), so code using them will be parsed with wrong types for these function calls.

It seems that adding them should be easy, however, there are some functions like `__builtin_add_overflow` which are declared like this:
```
bool __builtin_add_overflow(type1 a, type2 b, type3 *res)
```
`type1`, `type2`, and `type3` can be any integral type. How should this be represented inside CDT?

`__builtin_types_compatible_p`, which is also a builtin "function" with a signature that is not expressible in C , uses `""` as type for each parameter, which `createType(String)` seems to translate to a basic type with kind `eUnspecified` and no modifiers. Maybe this fits here as well? If yes, should the type of `res` be a void pointer or maybe something like `"*"`?

### PR DESCRIPTION
**Pull request by PhilippWendler**
Closes #271

The hidden comments below were the now resolved conversation on getting @PhilippWendler's ECA signed.

### CODE REVIEW

**Comment by PhilippWendler** [comment]
What does it mean "The author(s) of the pull request is not covered by necessary legal agreements in order to proceed."? The "Details" link just brings me to a login page.

[CONTRIBUTING.md](https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#copyright-license-and-provenance) only mentions a review process for more than 1000 lines of new code.

**Comment by jonahgraham** [comment]
Please sign the ECA, details in contributing guide https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement

PS The details link needs an Eclipse account to access.

**Comment by PhilippWendler** [comment]
Ah, there is a another section below in the documentation. That's easy to miss.

I signed it now.

**Comment by PhilippWendler** [comment]
Oh, I thought it would match my GitHub user name, given that it explicitly asks for that. And there seems to be no way to add multiple email addresses in your Eclipse account to sign the ECA for? So now it forces me to make my email address for that account public...

Well, I pushed again with the other mail address. Should work now.

**Comment by jonahgraham** [comment]
I don't know many people that do it this way, but IIRC if you make the author of your git commit your github username (the one that has the `@noreply` in it) then it matches on github usernames.

**Review by jonahgraham — APPROVED** [review]

**Comment by jonahgraham** [comment]
Thanks @PhilippWendler for the contribution. Now that your first one has been approved and merged, subsequent PRs will automatically run the GitHub Action workflows.

**Pull request merged**
