### PR TITLE
org.eclipse.cdt.target should have shortcut for CDTConfiguration.setup

### PR DESCRIPTION
**Pull request by ruspl-afed**
Added shortcut to CDTConfiguration.setup in order to resolve validation problems in CDT.setup

### CODE REVIEW

**Comment by jonahgraham** [comment]
This PR is fine to merge based on the CI results (benefit of three runs per PR :) - at some point it would be great if someone addressed the unstable tests.

PS. You may need to raise an issue with the [helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new) to delete the branch once you have merged it.

**Comment by jonahgraham** [comment]
> > PS. You may need to raise an issue with the [helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new) to delete the branch once you have merged it.
> 
> Oops, I thought branch deletion is allowed for committers, except "protected" branches.

I'm not sure. I guess we'll find out soon enough. When we were in gerrit all branches were protected. The exact branch protections on GitHub for CDT are still not quite right because there is nothing quite equivalent to require pushes to go via gerrit change.

**Comment by ruspl-afed** [comment]
Just checked the CONTRIBUTING.md that redirects me to https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#recommended-workflow

> The recommended way for contributions is to create a fork 

Well, it looks like I violated the recommendations, sorry for that.

**Review by jonahgraham — APPROVED** [review]
LGTM.

I don't think you need to wait for CI to merge this as I don't think anything in the CI will test this change anyway.

**Comment by ruspl-afed** [comment]
> PS. You may need to raise an issue with the [helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new) to delete the branch once you have merged it.

Done. https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2147

**Pull request merged**
