### PR TITLE
Propagate exceptions in default binary file viewer

### PR DESCRIPTION
**Pull request by jld01**
This PR ensures that any IOExceptions raised while generating content for the _Default Binary File Viewer_ are propagated up to UI code. It is the responsibility of the `IEditorPart` to determine how to present these exceptions to user.

### CODE REVIEW

**Comment by jld01** [comment]
The CI build logs indicate:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.3:compile (default-compile) on project org.eclipse.cdt.cmake.core: Compilation failure: Compilation failure: 
[ERROR] /home/runner/work/cdt/cdt/cmake/org.eclipse.cdt.cmake.core/src/org/eclipse/cdt/cmake/core/internal/CMakePropertiesController.java:[69] 
[ERROR] 	props = new Yaml(new CustomClassLoaderConstructor(this.getClass().getClassLoader())).loadAs(is,
[ERROR] 	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The constructor CustomClassLoaderConstructor(ClassLoader) is undefined
[ERROR] 1 problem (1 error)
```
The CDT target definition is providing org.yaml.snakeyaml 1.27.0 from Orbit which provides this constructor, but I see references to snakeyaml 2.0 from maven central in the CI logs.

Any ideas @jonahgraham?

**Comment by jonahgraham** [comment]
Hi John. I'll have a look tomorrow. No immediate ideas other than maybe an upper bound is missing in the manifest.

**Comment by jld01** [comment]
> Hi John. I'll have a look tomorrow. No immediate ideas other than maybe an upper bound is missing in the manifest.

Thanks, @jonahgraham. The single parameter `CustomClassLoaderConstructor` constructor was removed at: https://github.com/snakeyaml/snakeyaml/commit/3e755d254aeaa902675053047fd53368a175565a

If snakeyaml 2.0 is required elsewhere, it seems we could add `new LoaderOptions()` as a second parameter in the call from `CMakePropertiesController`.

**Comment by jonahgraham** [comment]
Please rebase/merge with main to pick up the snakeyaml fix in #436

**Pull request merged**
