### PR TITLE
Improve CDT's setup

### PR DESCRIPTION
**Pull request by merks**
Include a configuration, simplify the targlet for the target platform,
and enhance the working sets based on folder structure.

https://github.com/eclipse-cdt/cdt/issues/39

### CODE REVIEW

**Comment by merks** [comment]
@ruspl-afed Two test projects changed their imports so hopefully that works well with the build...

**Comment by merks** [comment]
@ruspl-afed I'm not sure I understand the two different builds with one passing and the other failing.  Neither of the failures are in the two test projects that I very slightly modified...

**Comment by merks** [comment]
@jonahgraham Once this is done, I'll be able to provide content for the contributing page...

**Comment by ruspl-afed** [comment]
Merging this one, not sure why pr-head has different test results

**Comment by jonahgraham** [comment]
> @ruspl-afed I'm not sure I understand the two different builds with one passing and the other failing. Neither of the failures are in the two test projects that I very slightly modified...

The two failed tests are flaky tests that haven't been [mitigted yet](https://github.com/eclipse-cdt/cdt/blob/main/TESTING.md#marking-tests-as-slow-or-flaky). The two builds are the result of testing this PR on its own (pr-head) and this PR automatically merged with main branch (pr-merge).

**Pull request merged**
