### PR TITLE
More test stability fixes

### PR DESCRIPTION
**Pull request by jonahgraham**
More work on #117

### CODE REVIEW

**Comment by jonahgraham** [comment]
Getting close here - both runs on Jenkins have 0 test errors.

**Comment by jonahgraham** [comment]
Yay! I finally reproduced testCommonSDK failing locally. Once I reduced my plug-ins to just required in the IDE then I got the same failure

image

**Comment by jonahgraham** [comment]
> Yay! I finally reproduced testCommonSDK failing locally. Once I reduced my plug-ins to just required in the IDE then I got the same failure

Not sure I reproduced the same issue anymore. This may have been because I was running without the managed builder plug-ins.

**Comment by mbooth101** [comment]
I appreciate the work you are putting in to fix the tests :+1:

**Comment by jonahgraham** [comment]
> 45 [:x:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols)

I know this looks worse - but it is because I added additional checks to make sure tests were not leaving files in the workspace. Many tests aren't deleting projects.

**Comment by jonahgraham** [comment]
I have split non-test changes out of this PR into new PRs, see #142, #143

**Comment by jonahgraham** [comment]
And #144 too.

**Pull request merged**
